### ISSUE TITLE
fps drop

### ISSUE THREAD

**Issue by gitaaron** [functionland/fotos#119]
When animations are repeated inside image cell - try using animated v1

Everything else - try using reanimated  v2

**Comment by ghorbani-m** [comment]
We are not able to use Animated from 'react-native' because we are using 'react-native-reanimated' v2 for this purpose and there is mismatching between these libraries because react-native Animated runs on the Js thread and reanimated runs on the UI thread.

The issue in our case is that when we scroll the list very fast, we use a recycling mechanism to support a large list by [recyclerlistview](https://github.com/Flipkart/recyclerlistview) and `useAnimatedStyle `to animate Cells.

`useAnimatedStyle `updater method calls every time dependencies are changed. so while we scroll the list very fast there are many updater methods that have to be updated because the dependencies are changed and it causes performance issues.

**Our solution to solve this issue is:**

1. Use [] as a dependency list in the useAnimatedStyle params (to prevent update when the component is rerendered)
```
const animationStyle = useAnimatedStyle(() => {
           ....
    }, [])
```
3. Update the dependencies with delay and revoke the changes if there is a new update.
```
useEffect(() => {
        clearTimeout(timerId.current)
        timerId.current = setTimeout(() => {
            timerId.current = null;
            sharedFinalRangeValues.value = layoutProvider.getLayoutManager()?.getLayoutTransitionRangeForIndex(index, columnNumber);
        }, 50);
    }, [index])
```
